docker 12
adding git pull to ./run rebuild

diff --git a/run b/run
--- a/run
+++ b/run
@@ -22,6 +22,21 @@ function get_dID {
 }
 
 
+function git_pull {
+
+    cd $DIR
+
+    git pull
+    if [ "$?" != 0 ]
+    then
+        echo "error while getting new updates"
+        exit
+    fi
+
+
+}
+
+
 if [ "$1" == "kill" ]
 then
 
@@ -58,6 +73,8 @@ then
 elif [ "$1" == "rebuild" ]
 then
 
+    git_pull
+
     cd $DIR/docker
 
     docker build --no-cache -t teahaz_server:latest .
@@ -65,12 +82,7 @@ then
 
 else
 
-    git pull
-    if [ "$?" != 0 ]
-    then
-        echo "error while getting new updates"
-        exit
-    fi
+    git_pull
 
     get_dID
 
